name: cctv_env
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.12.2=haa95532_0
  - expat=2.7.4=hd7fb8db_0
  - libexpat=2.7.4=hd7fb8db_0
  - libffi=3.4.4=hd77b12b_1
  - libzlib=1.3.1=h02ab6af_0
  - openssl=3.0.19=hbb43b14_0
  - packaging=25.0=py310haa95532_1
  - pip=26.0.1=pyhc872135_0
  - python=3.10.19=h981015d_0
  - setuptools=80.10.2=py310haa95532_0
  - sqlite=3.51.1=hda9a48d_0
  - tk=8.6.15=hf199647_0
  - tzdata=2025c=he532380_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.46.3=py310haa95532_0
  - xz=5.6.4=h4754444_1
  - zlib=1.3.1=h02ab6af_0
  - pip:
      - certifi==2026.1.4
      - charset-normalizer==3.4.4
      - contourpy==1.3.2
      - cycler==0.12.1
      - filelock==3.24.0
      - fonttools==4.61.1
      - fsspec==2026.2.0
      - idna==3.11
      - jinja2==3.1.6
      - kiwisolver==1.4.9
      - markupsafe==3.0.3
      - matplotlib==3.10.8
      - mpmath==1.3.0
      - networkx==3.4.2
      - numpy==2.2.6
      - opencv-python==4.13.0.92
      - pillow==12.1.1
      - polars==1.38.1
      - polars-runtime-32==1.38.1
      - psutil==7.2.2
      - pyparsing==3.3.2
      - pyqt6==6.10.2
      - pyqt6-qt6==6.10.2
      - pyqt6-sip==13.11.0
      - python-dateutil==2.9.0.post0
      - pyyaml==6.0.3
      - requests==2.32.5
      - scipy==1.15.3
      - six==1.17.0
      - sympy==1.14.0
      - torch==2.10.0
      - torchvision==0.25.0
      - typing-extensions==4.15.0
      - ultralytics==8.4.14
      - ultralytics-thop==2.0.18
      - urllib3==2.6.3
